name: Validate

on:
  pull_request:
  push:
    branches-ignore:
      - master

permissions: {}

jobs:
  validate:
    if: github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "Running on ${{ runner.os }}"
